---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-1
  namespace: virtualmachines
  labels:
    kubevirt-manager.io/managed: "true"
    kubevirt-manager.io/ssh: "true"
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    UG91cmluZzYlRW1vdGljb24lU2N1YmE=

---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-2
  namespace: virtualmachines
  labels:
    kubevirt-manager.io/managed: "true"
    kubevirt-manager.io/ssh: "true"
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    UG91cmluZzYlRW1vdGljb24lU2N1YmE=

---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-3
  namespace: virtualmachines
  labels:
    kubevirt-manager.io/managed: "true"
    kubevirt-manager.io/ssh: "true"
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    UG91cmluZzYlRW1vdGljb24lU2N1YmE=